### ISSUE TITLE
Please don't mixin other mods

### ISSUE THREAD

**Issue by mezz** [TeamDeusVult/MagnesiumExtras#26] opened 2022-07-23 23:57 UTC
```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [rubidium_extras.mixins.json:JEI.IngredientListOverlayMixin] from phase [DEFAULT] in config [rubidium_extras.mixins.json] FAILED during APPLY
```
I'm getting reports of issues from your mod applying mixins to JEI internal classes.
This isn't a safe thing to do, please find a more robust way to achieve what you're trying to do.

I'm also getting a lot of bug reports from confused users. 
I think you should reconsider altering JEI's default behaviors in a way that is confusing to people. 
It may be better as an opt-in option.

**Comment by PaterFrog** [comment] 2022-07-26 00:49
I believe I am one such user, please see here: https://github.com/mezz/JustEnoughItems/issues/2908#issuecomment-1193209321

**Comment by ambientNexus** [comment] 2022-07-26 08:40
Seriously, who even remotely thought this was a good idea to implement in a completely unrelated mod, let alone having it enabled by default?

**Comment by CassieRoseZA** [comment] 2022-07-26 11:05
> Seriously, who even remotely thought this was a good idea to implement in a completely unrelated mod, let alone having it enabled by default?

who knows

**Comment by Aspurgus** [comment] 2022-07-26 20:29
is there any setting in the config to disable it ?

**Comment by jmdev91** [comment] 2022-07-27 01:21
Ohhh, no wonder my recipe list in ATM7 lags so much.

**Comment by Mitchell5200** [comment] 2022-07-27 05:36
Adding my crash report to this too, MC 1.18.2, forge 40.1.60
Rubidium Extras v1.3.1.jar,
JEI jei-1.18.2-9.7.1.232.jar

[crash-2022-07-27_13.03.28-client.txt](https://github.com/TeamDeusVult/MagnesiumExtras/files/9195335/crash-2022-07-27_13.03.28-client.txt)

*edit* seems to be the same as #24 and #25

**Comment by Tander** [comment] 2022-07-27 15:07
+1

[crash-2022-07-27_17.44.13-client.txt](https://github.com/TeamDeusVult/MagnesiumExtras/files/9200323/crash-2022-07-27_17.44.13-client.txt) (reproduced on a clean setup)

Temporary workaround: use jei-1.18.2-9.7.0.209

**Comment by KazuMurako** [comment] 2022-07-29 06:30
Just found this problem in my game too, same as some others in this issue.
MC 1.18.2
forge 40.1.51
jei-1.18.2-9.7.1.232.jar
rubidium_extras-1.18.2_v1.3.1.jar
rubidium-0.5.3.jar
[crash-2022-07-29_00.21.29-client.txt](https://github.com/TeamDeusVult/MagnesiumExtras/files/9216853/crash-2022-07-29_00.21.29-client.txt)

**Comment by lofcz** [comment] 2022-07-31 04:54
Here's a quick patch by me for v1.3.1, removes the offending mixin. Just replace the jar file in your /mods and you can enjoy latest JEI (tested with jei-1.18.2-forge-10.1.3.240.jar)

[rubidium_extras-1.18.2_v1.3.1.zip](https://github.com/TeamDeusVult/MagnesiumExtras/files/9228074/rubidium_extras-1.18.2_v1.3.1.zip)

The patch:

![image](https://user-images.githubusercontent.com/10260230/182010792-81b47da5-28e0-4136-be00-45e130c9e10c.png)
![image](https://user-images.githubusercontent.com/10260230/182010796-18f5e4dc-306b-412e-8304-4190952594fc.png)

_Note for ATM7 fellas: JEI is currently capped at jei-1.18.2-9.7.1.232.jar due to lazierAE2_

**Comment by Tander** [comment] 2022-07-31 09:28
Sadly, probably won't be acceptable in modpacks in curseforge, moderation process will be painful

**Comment by SDUBZ** [comment] 2022-07-31 13:43
This really needs to be fixed O_O

**Comment by Charismara** [comment] 2022-08-01 08:25
same crash :(

**Comment by lynnpye** [comment] 2022-08-01 14:39
@lofcz I turned your change into a pull request (https://github.com/TeamDeusVult/MagnesiumExtras/pull/27)
ping @nthxny

**Comment by lofcz** [comment] 2022-08-01 23:34
@lynnpye I intentionally did not do that, as I reckon mod author might want to handle this in a better way, possibly preserving the feature.

**Comment by txnitxnichopper** [comment] 2022-08-01 23:39
> @lynnpye I intentionally did not do that, as I reckon mod author might want to handle this in a better way, possibly preserving the feature.

Yes, the patch needs to be updated and probably set to optional so it doesn't crash if the targeting breaks. I have just been extremely busy and have not gotten around to this. 

The feature will stay. It improves performance in the menu and looks much nicer. If modpack devs don't like it, they can turn it off. 

I'll add an option in the settings menu for it so it's not hidden in the config. That should maybe help reduce bug reports on JEI's end, but honestly they should just implement this on their end. Been so much nicer playing modded ever since I added it.

**Comment by Tander** [comment] 2022-08-01 23:51
I have this feature of RubidiumExtras disabled and still crashing. Which exactly parameters I should change to make it work with up-to-date JEI?

**Comment by ChiefArug** [comment] 2022-08-02 01:36
> If modpack devs don't like it, they can turn it off. 

Please do not do it like this. Make it opt in rather than opt out.
As mezz said, changing default behaviour is not a good idea.

**Comment by txnitxnichopper** [comment] 2022-08-02 01:40
I believe the default behavior should be to hide the items until searching (for many reasons). If people don't like it, they don't have to install the mod, or can toggle it off.

**Comment by Foxydapirate12** [comment] 2022-08-02 06:54
Having the same issue here: https://bytebin.lucko.me/YI7lSthkYK

**Comment by lofcz** [comment] 2022-08-02 09:01
> I believe the default behavior should be to hide the items until searching (for many reasons). If people don't like it, they don't have to install the mod, or can toggle it off.

@nthxny while I agree that it looks better to hide JEI items until search is active and that the performance benefit is there (although not rendering a few cached images isn't marginal), there is a clear demand for this feature to be opt-in. Also I believe (correct me if I'm wrong) that there is no way sans mixins to do this in a robust manner with no support on JEI side.

So maybe we could prepare a PR for JEI and make this feature opt-in there?

@mezz would you be open to this?

**Comment by Tander** [comment] 2022-08-02 12:49
Small remark: This feature, as it is implemented currently in RubidiumExtras, makes JEI look broken. It should display at least a message, like "Use Search firld to display items" or something similar, not just empty space.

**Comment by rjulib00** [comment] 2022-08-02 16:58
> Here's a quick patch by me for v1.3.1, removes the offending mixin. Just replace the jar file in your /mods and you can enjoy latest JEI (tested with jei-1.18.2-forge-10.1.3.240.jar)
> 
> [rubidium_extras-1.18.2_v1.3.1.zip](https://github.com/TeamDeusVult/MagnesiumExtras/files/9228074/rubidium_extras-1.18.2_v1.3.1.zip)
> 
> The patch:
> 
> ![image](https://user-images.githubusercontent.com/10260230/182010792-81b47da5-28e0-4136-be00-45e130c9e10c.png) ![image](https://user-images.githubusercontent.com/10260230/182010796-18f5e4dc-306b-412e-8304-4190952594fc.png)
> 
> _Note for ATM7 fellas: JEI is currently capped at jei-1.18.2-9.7.1.232.jar due to lazierAE2_

thx mate, it work, dik who has the problem and dont know who has to fix, but for the moment, this will do, thx again ;)

**Comment by mezz** [comment] 2022-08-02 17:33
JEI is open source and open to contributions, the right way to go about this is to hop into Discord and talk about it with me and others, and then open a PR once we figure out a good way to do it.

I have considered adding this as a config option in the past, but it needs some actual design work in order to be a proper feature, otherwise it's just a half-done thing that's messing with people. Doubly confusing is the fact that this is coming from an unrelated mod, not JEI. How are people supposed to even discover this and remove your mod? Players are relying on snippets of information passed around by hand in the community, or reporting bugs to me, trying to overcome lack of care in creating this feature.

JEI should not display explanatory text on the screen directly, so perhaps the right design here would be to add an icon in the middle of the search area, that has a tooltip when you hover over it like "Search to display items". Or add another button near the config button that toggles this behavior, with an eye open/closed icon on it or something. Again, it can have a tooltip to explain the behavior clearly. Maybe those are both bad, and it'll take more work to get to the right solution, but the point is, this design step and direct communication to the players is a necessary part of creating a feature like this.

The other necessary part of creating a feature like this is that it must be robust. If you want to poke into the internals of JEI, you bear the responsibility of not breaking it. People rely on JEI just working, pretty much all the time no matter what bizarre broken stuff other mods are doing. I've put a lot of work into making that happen, and it's frustrating to see this. Thinking collaboratively and adding this feature to JEI would be the best way to ensure it doesn't break.

**Comment by serialtasted** [comment] 2022-08-03 00:03
> > @lynnpye I intentionally did not do that, as I reckon mod author might want to handle this in a better way, possibly preserving the feature.
> 
> Yes, the patch needs to be updated and probably set to optional so it doesn't crash if the targeting breaks. I have just been extremely busy and have not gotten around to this.
> 
> The feature will stay. It improves performance in the menu and looks much nicer. If modpack devs don't like it, they can turn it off.
> 
> I'll add an option in the settings menu for it so it's not hidden in the config. That should maybe help reduce bug reports on JEI's end, but honestly they should just implement this on their end. Been so much nicer playing modded ever since I added it.

I agree that you keep the feature. But you could publish an hotfix for now and work on the feature and release it later fully working instead of this limping state where we can't run the game.

**Comment by Foxydapirate12** [comment] 2022-08-03 13:56
> > I believe the default behavior should be to hide the items until searching (for many reasons). If people don't like it, they don't have to install the mod, or can toggle it off.
> 
> @nthxny while I agree that it looks better to hide JEI items until search is active and that the performance benefit is there (although not rendering a few cached images isn't marginal), there is a clear demand for this feature to be opt-in. Also I believe (correct me if I'm wrong) that there is no way sans mixins to do this in a robust manner with no support on JEI side.
> 
> So maybe we could prepare a PR for JEI and make this feature opt-in there?
> 
> @mezz would you be open to this?

I tried disabling that feature but it still crashed

**Comment by lynnpye** [comment] 2022-08-03 19:05
> > > I believe the default behavior should be to hide the items until searching (for many reasons). If people don't like it, they don't have to install the mod, or can toggle it off.
> > 
> > 
> > @nthxny while I agree that it looks better to hide JEI items until search is active and that the performance benefit is there (although not rendering a few cached images isn't marginal), there is a clear demand for this feature to be opt-in. Also I believe (correct me if I'm wrong) that there is no way sans mixins to do this in a robust manner with no support on JEI side.
> > So maybe we could prepare a PR for JEI and make this feature opt-in there?
> > @mezz would you be open to this?
> 
> I tried disabling that feature but it still crashed

As it currently stands, the code that mixes into JEI so that this mod is even capable of changing the JEI functionality, and therefore must always be run, is what is breaking. That code is setup before config options are read and is not subject to being disabled.

Disabling the feature via this mod's config options just tells this mod not to actually try to *use* that code to change the JEI functionality. But of course, by that time, the damage is done.

As a result, even attempting to run this mod with JEI installed, with or without disabling the feature via config, will simply cause your instance to crash to desktop.

**Comment by Canada-LaVearn** [comment] 2022-08-05 17:51
So do we know if the mod dev plans to fix this or is it just broken

**Comment by LordSeabass** [comment] 2022-08-11 04:04
Having the same issue

**Comment by Chaos02** [comment] 2022-08-14 17:31
Total issue with FLUID handling recipes because they require JEI <v10:
https://github.com/TeamDeusVult/MagnesiumExtras/issues/25#issuecomment-1214419521

**Comment by ambientNexus** [comment] 2022-08-14 22:50
> I believe the default behavior should be to hide the items until searching (for many reasons). If people don't like it, they don't have to install the mod, or can toggle it off.

It is a feature added to a completely unrelated mod, that is not only hidden in the config, but also actively causes issues for other users due to its implementation. @nthxny Considering you seem to be highly insistent on keeping it in, why not just separate it from this mod and add it to a personal mod for yourself? Is that seriously so much of an issue to do, considering it would be the best option overall?

**Comment by txnitxnichopper** [comment] 2022-08-15 19:21
fixed in latest release

**Closed as completed by txnitxnichopper** 2022-08-15 19:21 UTC
